In [1]:
import numpy as np
import matplotlib.pyplot as plt
% matplotlib inline

# Introduction

Procedures to be used

In [2]:
# outcome of one coin flip
np.random.randint(2)

1

In [3]:
# outcomes of ten thousand coin flips
np.random.randint(2, size=10000)

array([1, 1, 1, ..., 0, 1, 0])

In [4]:
# mean outcome of ten thousand coin flips
np.random.randint(2, size=10000).mean()

0.49640000000000001

In [5]:
# outcome of one coin flip
np.random.choice([0, 1])

1

In [6]:
# outcome of ten thousand coin flips
np.random.choice([0, 1], size=10000)

array([1, 1, 0, ..., 1, 0, 0])

In [7]:
# mean outcome of ten thousand coin flips
np.random.choice([0, 1], size=10000).mean()

0.5071

In [8]:
# outcomes of ten thousand biased coin flips
np.random.choice([0, 1], size=10000, p=[0.8, 0.2])

array([0, 1, 0, ..., 0, 0, 0])

In [9]:
# mean outcome of ten thousand biased coin flips
np.random.choice([0, 1], size=10000, p=[0.8, 0.2]).mean()

0.19750000000000001

# Probability Quiz

In this quiz, you will simulate coin flips and die rolls to compute proportions for the following outcomes.

* Two fair coin flips produce exactly two heads
* Three fair coin flips produce exactly one head
* Three biased coin flips with P(H) = 0.6 produce exactly one head
* A die rolls an even number
* Two dice roll a double
* Then, you'll compare these proportions with probabilities in the quizzes below.

When simulating coin flips, use 0 to represent heads and 1 to represent tails. When simulating die rolls, use the correct integers to match the numbers on the sides of a standard 6 sided die.



### 1. Two fair coin flips produce exactly two heads

In [10]:
# simulate 1 million tests of two fair coin flips
tests = np.random.randint(2, size=(int(1e6),2))

# sums of all tests
test_sums = tests.sum(axis=1)

# proportion of tests that produced exactly two heads
(test_sums == 0).mean()


0.25039800000000001

### 2. Three fair coin flips produce exactly one head

In [11]:
# simulate 1 million tests of three fair coin flips
tests = np.random.randint(2, size=(int(1e6),3))

# sums of all tests
test_sums = tests.sum(axis=1)

# proportion of tests that produced exactly one head
(test_sums==2).mean()

0.375386

### 3. Three biased coin flips with P(H) = 0.6 produce exactly one head

In [12]:
# simulate 1 million tests of three bias coin flips
# hint: use np.random.choice()
tests = np.random.choice([0, 1], size=(int(1e6),3), p=[0.6, 0.4])

# sums of all tests
test_sums = tests.sum(axis = 1)

# proportion of tests that produced exactly one head
(test_sums==2).mean()

0.287719

### 4. A die rolls an even number

In [9]:
# simulate 1 million tests of one die roll
tests = np.random.choice([1,2,3,4,5,6], size=(int(1e6)))

# proportion of tests that produced an even number
np.isin(tests,[2,4,6]).mean()

0.50036800000000003

### 5. Two dice roll a double

In [17]:
# simulate the first million die rolls
first = np.random.choice([1,2,3,4,5,6], size=(int(1e6)))

# simulate the second million die rolls
second = np.random.choice([1,2,3,4,5,6], size=(int(1e6)))

# proportion of tests where the 1st and 2nd die rolled the same number
(first==second).mean()

0.16676199999999999